### ISSUE TITLE
Dugr 4 Beta: Create,Remove, Rename Group Buttons UI

### ISSUE THREAD

**Issue by popevideo** [RxLaboratory/DuAEF_DuGR#31]
Is it possible to use the old Create Group, Delete Group, Rename group buttons and placement from Dugr 3?
 The Create new group Pop Up on Dugr 4 to me takes more steps. 

**Dugar 4 Steps**
1.You have to click the create new group button
2.then click the name field.
3.Name group
4.Click Ok Button

**Dugar 3 Steps**
1. Click the new group name field
2. Name group and press enter key

I think the placement on the bottom is a better place as well.

<img width="289" alt="Screen Shot 2021-07-30 at 12 08 05 PM" src="https://user-images.githubusercontent.com/46870817/127701045-31946d15-3604-44f6-be49-8014c164f82f.png">

**Comment by Nico-Duduf** [comment]
I've already improved it in the next version, and you don't have to click the name field anymore (it's already activated when you click the create button)
I'm trying to make the "enter" key work to be able to validate the creation like that instead of having to click OK, but there's some kind of bug in After Effects preventing the key to be detected. I may be able to fix that
