### ISSUE TITLE
It would be great to have a little more room in the UI

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_DuGR#35]
Dear Nicolas!

First of all thank you for all the hard work that went into reimagining DuGR. It is quite powerful. I like the many options users can choose from.

The icon navigation is great but I think it could benefit from being a bit more spaced out. Especially with the type under certain icons the room gets too tight and adds visual tension.

Also a clearer division between the horizontal icon groups would help the user differentiate things more. I think the top and middle icon group could also benefit from a justified alignment.

The »x« (exit isolation) in the top row is a little off.

![DUGR-ui](https://user-images.githubusercontent.com/38455050/128778266-7805b27b-e9f9-4d7e-aeb0-af3d1fdabb9d.jpg)

**Comment by Nico-Duduf** [comment]
thanks for the detailed feedback! I'm working on it ;)
I'm not sure I can justify the buttons like that because of the way Ae script layout works but I surely can improve the UI thanks to your suggestions.

one thing that bothers me is that the two lines of small attribute buttons should have a lighter background. I think it may be that we don't have the same setting for the interface lightness and the script doesn't take that into account, but I should be able to fix that. can you just confirm that your setting in the ae prefs is not to the lowest value?

**Comment by reneandritsch** [comment]
Dear Nicolas, please see my screenshot for my brightness level in AE

![Bildschirmfoto 2021-08-10 um 14 22 04](https://user-images.githubusercontent.com/38455050/128865969-6d72bb50-f8a5-4616-8f30-77b732c88297.png)

**Comment by Nico-Duduf** [comment]
Perfect thanks!
That should be fixed in the next version :)

**Comment by reneandritsch** [comment]
Thanks!
